server:
  port: 8080

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

kafka:
  bootstrap-servers: 172.16.123.1:9092

connector:
  topics:
    app: createClient

response:
  synchronous: false