server:
  port: 8080

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

kafka:
  bootstrap-servers: ec2-34-243-24-159.eu-west-1.compute.amazonaws.com:9092

connector:
  topics:
    app: createClient

response:
  synchronous: false